services:
  db:
    image: postgres:16
    container_name: docuflow-db
    restart: always
    environment:
      POSTGRES_USER: docuflow
      POSTGRES_PASSWORD: docuflow
      POSTGRES_DB: docuflow
    ports:
      - "5432:5432"
    volumes:
      - docuflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docuflow -d docuflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: docuflow-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Esta URL se usar√° tanto en FastAPI como en Alembic
      DATABASE_URL: postgresql://docuflow:docuflow@db:5432/docuflow
      JWT_SECRET_KEY: super_secret_dev_key
    ports:
      - "8000:8000"
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A app.core.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: unless-stopped

volumes:
  docuflow_db_data:
