services:
  db:
    image: postgres:16
    container_name: docuflow-db
    restart: always
    environment:
      POSTGRES_USER: docuflow
      POSTGRES_PASSWORD: docuflow
      POSTGRES_DB: docuflow
    ports:
      - "5432:5432"
    volumes:
      - docuflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docuflow -d docuflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: docuflow-redis
    restart: unless-stopped

  api:
    build: .
    container_name: docuflow-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      # si quieres sobreescribir algo de .env, puedes hacerlo aqu√≠
      DATABASE_URL: postgresql://docuflow:docuflow@db:5432/docuflow
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    container_name: docuflow-worker
    command: celery -A app.core.celery_app.celery_app worker -Q documents -l info
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: docuflow-beat
    command: celery -A app.core.celery_app.celery_app beat -l info
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  docuflow_db_data:
